### PR TITLE
Added option to switch volume slider to the right side of the screen

### PR DESCRIPTION
**Pull request by Anthonyy232**
Implemented the right side volume slider
- Added boolean to player preferences
- Added appropriate slider and title to the settings page
- Modified the PlayerControls.kt to support each case

### CODE REVIEW

**Comment by Anthonyy232** [comment]
Screenshot_20241010_211527_mpvKt
Screenshot_20241010_211626_mpvKt

**Comment by abdallahmehiz** [comment]
wouldn't making an option to "swap" the sliders be better?

**Comment by Anthonyy232** [comment]
What do you mean? There's a switch item in the settings page that when toggled, changes the volume slider to the right (default is off, left -- as you intended I imagine)

**Comment by abdallahmehiz** [comment]
My intention was to switch them so the brightness slider goes to the left and volume slider goes to the right. 
Cause it became kind of busy at the right side of the screen with the way you've implemented it.

**Comment by Anthonyy232** [comment]
Ah, understood. Then for the brightness, I guess I can check if volume is on the right, then I'll move it to the left. However, this may become a little messy down the line if you also want to add the option to swap the brightness slider to the left. I dunno. 

I'll add it in a bit

**Comment by abdallahmehiz** [comment]
> Ah, understood. Then for the brightness, I guess I can check if volume is on the right, then I'll move it to the left. However, this may become a little messy down the line if you also want to add the option to swap the brightness slider to the left. I dunno.
> 
> I'll add it in a bit, and also do the string thing

It'll probably be ok, just rename the preference to swap brightness and volume sliders positions. It'd probably be simpler

**Comment by Anthonyy232** [comment]
Done, also fixed the gesture being on the wrong side

**Comment by abdallahmehiz** [comment]
Thank you for your contribution

**Pull request merged**
