### PR TITLE
Added support for control with bluetooth pause/play buttons

### PR DESCRIPTION
**Pull request by Anthonyy232**
Implemented bluetooth pause/play with MediaSession
- Tested on S24 Ultra with Galaxy Buds 2 Pro

### CODE REVIEW

**Comment by Anthonyy232** [comment]
Should I add a switch preference for this? Or would you want it automatically enabled for everyone?

**Comment by Eve9181** [comment]
hey,i just checked the controls works fine but the video doesn't get paused when bluetooth headset is disconnected like other players,so could you make it so it does that?

**Comment by Anthonyy232** [comment]
Probably, that would require registering a broadcast receiver and catching the noisy intent. Not sure if the author would be okay with that

**Comment by abdallahmehiz** [comment]
> Probably, that would require registering a broadcast receiver and catching the noisy intent. Not sure if the author would be okay with that

You can go for it.
> Also as a side note, the app seems to have a delay when pausing and starting (seems to skip frames or something?)

Yes, mpv does sometimes skip frames when resuming videos.

**Comment by Anthonyy232** [comment]
Ready for review-merge

**Review by abdallahmehiz — APPROVED** [review]

**Pull request merged**
